### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by bunnyyTheFreak** [DotOS/android_packages_apps_Launcher3#1]
packages/apps/Launcher3/res/values/colors.xml:67: error: Error: No resource found that matches the given name (at 'fastscroller_thumb_text_color' with value '@*android:color/updater_snackbar_text_color').

**Comment by SharkEzz** [comment]
Same here

**Comment by mohancm** [comment]
It's on our Gerrit. Tomorrow it will be merged.
If you really want to compile now,pick this commit.
https://gerrit.droidontime.com/#/c/DotOS/android_frameworks_base/+/2132/

Thanks
